"""Course catalog data for the Institute Management System.

Extracted from constants.py to keep the main constants file focused on
application configuration. The AVAILABLE_COURSES list contains detailed
course definitions including modules, topics, prerequisites, and outcomes.
"""

AVAILABLE_COURSES = [
    {
        "code": "DSA",
        "name": "Data Structures & Algorithms",
        "duration": 6,
        "fee": 35000,
        "description": "Master the fundamentals of computer science with our comprehensive Data Structures & Algorithms course. This program is designed to build strong problem-solving skills and prepare students for technical interviews at top tech companies. You will learn to implement and optimize a wide range of data structures and algorithms from scratch.",
        "prerequisites": [
            "Basic knowledge of any programming language",
            "Familiarity with variables, loops, and functions",
        ],
        "learning_outcomes": [
            "Implement all major data structures from scratch",
            "Analyze time and space complexity using Big-O notation",
            "Solve 100+ coding problems across various topics",
            "Master recursive and dynamic programming techniques",
            "Crack technical interviews at FAANG and top product companies",
        ],
        "career_opportunities": [
            "Software Engineer",
            "Backend Developer",
            "Systems Engineer",
            "Competitive Programmer",
        ],
        "modules": [
            {
                "title": "Module 1: Foundations & Complexity Analysis",
                "duration_weeks": 3,
                "topics": [
                    "Introduction to Algorithms & Problem Solving",
                    "Asymptotic Analysis: Big-O, Big-Omega, Big-Theta",
                    "Space vs Time Complexity Trade-offs",
                    "Mathematics for DSA: Logarithms, Exponentials, Series",
                    "Recursion: Concepts, Tree Recursion, Tail Recursion",
                    "Backtracking: N-Queens, Rat in a Maze, Sudoku Solver",
                    "Divide and Conquer Strategy",
                    "Practice: 20+ beginner algorithmic problems",
                ],
            },
            {
                "title": "Module 2: Linear Data Structures",
                "duration_weeks": 4,
                "topics": [
                    "Arrays: 1D, 2D, Dynamic Arrays, Rotation, Reversal",
                    "Strings: Pattern Matching, KMP Algorithm, Rabin-Karp",
                    "Linked Lists: Singly, Doubly, Circular, Reversal, Detection of Cycles",
                    "Stacks: Array & Linked List Implementation, Applications (Parenthesis Matching, Infix/Postfix)",
                    "Queues: Linear Queue, Circular Queue, Priority Queue, Deque",
                    "Practice: 30+ problems on linear data structures",
                ],
            },
            {
                "title": "Module 3: Non-Linear Data Structures",
                "duration_weeks": 4,
                "topics": [
                    "Trees: Binary Trees, Binary Search Trees, Tree Traversals (Inorder, Preorder, Postorder)",
                    "AVL Trees: Rotations, Balancing, Insertion & Deletion",
                    "Red-Black Trees: Properties, Insertion, Deletion",
                    "B-Trees & B+ Trees: Multi-way Search Trees",
                    "Heaps: Min-Heap, Max-Heap, Heap Sort, Priority Queue Implementation",
                    "Trie: Prefix Tree, Auto-complete, Spell Checker",
                    "Graphs: Adjacency Matrix & List, BFS, DFS, Topological Sort",
                    "Practice: 40+ problems on non-linear data structures",
                ],
            },
            {
                "title": "Module 4: Advanced Algorithms & Optimization",
                "duration_weeks": 4,
                "topics": [
                    "Sorting Algorithms: Quick Sort, Merge Sort, Radix Sort, Counting Sort",
                    "Searching Algorithms: Binary Search Variants, Ternary Search",
                    "Dynamic Programming: Memoization, Tabulation, Knapsack, LCS, LIS, Edit Distance",
                    "Greedy Algorithms: Activity Selection, Huffman Coding, Dijkstra's Algorithm",
                    "Graph Algorithms: Dijkstra, Bellman-Ford, Floyd-Warshall, Prim's, Kruskal's",
                    "Disjoint Set Union (Union-Find): Path Compression, Union by Rank",
                    "Segment Trees & Fenwick Trees",
                    "Practice: 50+ advanced algorithmic problems",
                ],
            },
            {
                "title": "Module 5: Interview Preparation & Capstone",
                "duration_weeks": 3,
                "topics": [
                    "Company-wise Previous Year Questions (FAANG, Microsoft, Amazon)",
                    "System Design Fundamentals for Algorithm Engineers",
                    "Mock Interviews & Whiteboard Practice",
                    "Competitive Programming Tips & Tricks",
                    "Capstone Project: Build a Real-world Algorithm Library",
                    "Final Assessment & Certification",
                ],
            },
        ],
    },
    {
        "code": "WEBJ",
        "name": "Web Dev with Java (Full Stack)",
        "duration": 8,
        "fee": 45000,
        "description": "Become a complete Full Stack Java Developer with this intensive 8-month program. Learn front-end technologies (HTML, CSS, JavaScript) alongside Java back-end development using Spring Boot. Build enterprise-level web applications with RESTful APIs, microservices architecture, and modern databases.",
        "prerequisites": [
            "Basic computer literacy",
            "Logical thinking and problem-solving skills",
        ],
        "learning_outcomes": [
            "Build responsive web interfaces using HTML5, CSS3, and JavaScript",
            "Develop robust back-end services with Java and Spring Boot",
            "Design and implement RESTful APIs and microservices",
            "Work with both SQL and NoSQL databases",
            "Deploy full-stack applications to cloud platforms",
        ],
        "career_opportunities": [
            "Full Stack Java Developer",
            "Backend Developer",
            "Spring Boot Developer",
            "Enterprise Application Developer",
        ],
        "modules": [
            {
                "title": "Module 1: Front-End Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "HTML5: Semantic Elements, Forms, Media Elements, APIs",
                    "CSS3: Flexbox, Grid, Animations, Transitions, Responsive Design",
                    "JavaScript ES6+: Variables, Functions, Objects, Arrays, Promises, Async/Await",
                    "DOM Manipulation & Event Handling",
                    "Bootstrap 5: Grid System, Components, Utilities",
                    "Version Control with Git & GitHub",
                    "Project: Build a Complete Responsive Business Website",
                ],
            },
            {
                "title": "Module 2: Core Java Programming",
                "duration_weeks": 5,
                "topics": [
                    "Java Fundamentals: Data Types, Operators, Control Flow",
                    "OOP Concepts: Classes, Objects, Inheritance, Polymorphism, Abstraction, Encapsulation",
                    "Exception Handling & Custom Exceptions",
                    "Collections Framework: List, Set, Map, Queue",
                    "Generics, Lambda Expressions & Streams API",
                    "Multithreading & Concurrency",
                    "File I/O & Serialization",
                    "Java 8+ Features: Optional, Date/Time API, Functional Interfaces",
                ],
            },
            {
                "title": "Module 3: Advanced Java & Database",
                "duration_weeks": 5,
                "topics": [
                    "JDBC: Database Connectivity, Connection Pooling",
                    "SQL: DDL, DML, Joins, Subqueries, Indexes, Transactions",
                    "MySQL Workbench & Database Design",
                    "Hibernate ORM: Entities, Relationships, Caching, HQL",
                    "JPA (Java Persistence API)",
                    "Project: E-Commerce Database Design & Implementation",
                ],
            },
            {
                "title": "Module 4: Spring Boot & REST APIs",
                "duration_weeks": 5,
                "topics": [
                    "Spring Core: IoC, DI, Beans, Scopes",
                    "Spring Boot: Auto-Configuration, Starters, Actuator",
                    "REST API Design Principles & Best Practices",
                    "Spring MVC: Controllers, Services, Repositories",
                    "Spring Data JPA: Query Methods, Specifications, Auditing",
                    "Spring Security: Authentication, Authorization, JWT",
                    "API Documentation with Swagger/OpenAPI",
                    "Project: Build a Complete RESTful Backend",
                ],
            },
            {
                "title": "Module 5: Microservices & Deployment",
                "duration_weeks": 4,
                "topics": [
                    "Microservices Architecture Principles",
                    "Spring Cloud: Service Discovery, API Gateway, Config Server",
                    "Docker: Containers, Images, Docker Compose",
                    "Message Queues: RabbitMQ, Kafka",
                    "Unit Testing with JUnit 5 & Mockito",
                    "CI/CD Pipeline with Jenkins & GitHub Actions",
                    "Cloud Deployment: AWS EC2, RDS, S3",
                    "Capstone Project: Full Stack Enterprise Application",
                ],
            },
        ],
    },
    {
        "code": "WEBP",
        "name": "Web Dev with Python (Django)",
        "duration": 8,
        "fee": 45000,
        "description": "Learn Full Stack Web Development with Python's most popular web framework Django. This course covers everything from HTML/CSS front-end to Django back-end, REST APIs with Django REST Framework, and deploying to the cloud. Build real-world projects including social media platforms, e-commerce sites, and content management systems.",
        "prerequisites": [
            "Basic computer skills",
            "Familiarity with programming concepts",
        ],
        "learning_outcomes": [
            "Build dynamic websites with Django's MTV architecture",
            "Create RESTful APIs using Django REST Framework",
            "Implement authentication, authorization, and security",
            "Work with PostgreSQL, Redis, and caching systems",
            "Deploy Python web applications to production",
        ],
        "career_opportunities": [
            "Python Full Stack Developer",
            "Django Developer",
            "Backend Engineer",
            "DevOps Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Web Fundamentals & Python",
                "duration_weeks": 4,
                "topics": [
                    "Internet Fundamentals: HTTP/HTTPS, DNS, Client-Server Architecture",
                    "HTML5: Semantic Markup, Forms, APIs",
                    "CSS3: Styling, Flexbox, Grid, Responsive Design",
                    "JavaScript Basics: DOM, Events, Fetch API",
                    "Python Refresher: Data Types, Functions, OOP, Modules",
                    "Python Advanced: Decorators, Generators, Context Managers",
                    "Virtual Environments & Package Management with pip",
                ],
            },
            {
                "title": "Module 2: Django Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "Django Architecture: MVT Pattern, Project vs App",
                    "URL Routing: URLconfs, Named URLs, Namespaces",
                    "Views: Function-Based Views, Class-Based Views, Generic Views",
                    "Templates: Django Template Language, Template Inheritance, Filters",
                    "Models: ORM, Migrations, Relationships (ForeignKey, ManyToMany, OneToOne)",
                    "Forms: ModelForms, Form Validation, Widgets",
                    "Admin Interface: Customization, Inlines, Actions",
                    "Project: Blog Application with Full CRUD",
                ],
            },
            {
                "title": "Module 3: Advanced Django & Security",
                "duration_weeks": 5,
                "topics": [
                    "Authentication: User Model, Login/Logout, Password Management",
                    "Authorization: Permissions, Groups, Custom User Model",
                    "Sessions & Messages Framework",
                    "File Uploads: ImageField, FileField, Media Files",
                    "Signals: Built-in & Custom Signals",
                    "Middleware: Custom Middleware Development",
                    "Security: CSRF, XSS, SQL Injection Prevention, HTTPS",
                    "Caching: Memcached, Redis, Cache Framework",
                    "Project: E-Commerce Platform",
                ],
            },
            {
                "title": "Module 4: Django REST Framework & APIs",
                "duration_weeks": 4,
                "topics": [
                    "RESTful API Design Principles",
                    "Django REST Framework: Serializers, Viewsets, Routers",
                    "Authentication in APIs: Token, JWT, Session",
                    "Permissions & Throttling",
                    "Filtering, Searching, Ordering",
                    "API Documentation with drf-spectacular",
                    "Testing APIs with Postman & pytest",
                    "Project: Social Media API",
                ],
            },
            {
                "title": "Module 5: Deployment & DevOps",
                "duration_weeks": 4,
                "topics": [
                    "PostgreSQL: Setup, Configuration, Advanced Queries",
                    "Environment Variables & Settings Management",
                    "Docker: Containerization of Django Apps",
                    "Nginx & Gunicorn: Production Server Setup",
                    "AWS: EC2, RDS, S3 Static Files, Elastic Beanstalk",
                    "CI/CD: GitHub Actions, Automated Testing",
                    "Monitoring: Sentry, Logging, Performance Optimization",
                    "Capstone Project: Production-Ready Web Application",
                ],
            },
        ],
    },
    {
        "code": "MERN",
        "name": "MERN Stack Development",
        "duration": 10,
        "fee": 55000,
        "description": "Master the most popular JavaScript stack — MongoDB, Express.js, React, and Node.js. This comprehensive 10-month program takes you from JavaScript fundamentals to building full-stack single-page applications. Learn modern front-end development with React Hooks, state management with Redux, and scalable back-end APIs with Node.js and Express.",
        "prerequisites": [
            "Basic programming knowledge",
            "Familiarity with web concepts",
        ],
        "learning_outcomes": [
            "Build modern single-page applications with React 18",
            "Create scalable REST APIs with Node.js and Express",
            "Design schemas and work with MongoDB (NoSQL)",
            "Implement full authentication and authorization systems",
            "Deploy MERN applications to cloud platforms",
        ],
        "career_opportunities": [
            "MERN Stack Developer",
            "React Developer",
            "Node.js Backend Developer",
            "Full Stack JavaScript Developer",
        ],
        "modules": [
            {
                "title": "Module 1: JavaScript Deep Dive",
                "duration_weeks": 5,
                "topics": [
                    "ES6+ Syntax: Arrow Functions, Destructuring, Spread/Rest",
                    "Asynchronous JavaScript: Callbacks, Promises, Async/Await",
                    "Closures, Scope, Hoisting, Event Loop",
                    "Prototypal Inheritance & Classes",
                    "Modules: ES Modules, CommonJS",
                    "Error Handling & Debugging",
                    "Package Managers: npm & yarn",
                    "Project: JavaScript Utility Library",
                ],
            },
            {
                "title": "Module 2: React Front-End Development",
                "duration_weeks": 6,
                "topics": [
                    "React Fundamentals: JSX, Components, Props, State",
                    "React Hooks: useState, useEffect, useContext, useReducer",
                    "Custom Hooks Development",
                    "Conditional Rendering & Lists",
                    "Forms: Controlled Components, Form Libraries (Formik, React Hook Form)",
                    "React Router v6: Routing, Navigation, Guards",
                    "State Management: Context API vs Redux Toolkit",
                    "Styling: CSS Modules, Styled Components, Tailwind CSS",
                    "Project: Task Management Dashboard",
                ],
            },
            {
                "title": "Module 3: Node.js & Express Backend",
                "duration_weeks": 5,
                "topics": [
                    "Node.js: Event Loop, Streams, File System, Buffers",
                    "Express.js: Routing, Middleware, Error Handling",
                    "REST API Design & Best Practices",
                    "Authentication: JWT, OAuth 2.0, Sessions",
                    "File Uploads: Multer, Cloud Storage Integration",
                    "WebSockets with Socket.io",
                    "Testing: Jest, Supertest, Integration Tests",
                    "Project: Blog Platform API",
                ],
            },
            {
                "title": "Module 4: MongoDB & Database Design",
                "duration_weeks": 4,
                "topics": [
                    "NoSQL Concepts: Document Store, Collections, Documents",
                    "MongoDB: CRUD Operations, Aggregation Pipeline",
                    "Mongoose ODM: Schemas, Models, Validation",
                    "Relationships: Embedding vs Referencing",
                    "Indexing & Performance Optimization",
                    "MongoDB Atlas: Cloud Database Setup",
                    "Redis: Caching, Session Store",
                ],
            },
            {
                "title": "Module 5: Advanced Topics & Deployment",
                "duration_weeks": 5,
                "topics": [
                    "GraphQL: Schemas, Resolvers, Apollo Server & Client",
                    "TypeScript with React & Node.js",
                    "Next.js: SSR, SSG, API Routes",
                    "Docker: Multi-Container MERN Setup",
                    "AWS: EC2, S3, CloudFront, Route 53",
                    "CI/CD: GitHub Actions, Automated Deployment",
                    "Performance Optimization: Lazy Loading, Code Splitting",
                    "Capstone Project: Full Stack E-Commerce Platform",
                ],
            },
        ],
    },
    {
        "code": "DS",
        "name": "Data Science with Python",
        "duration": 12,
        "fee": 65000,
        "description": "Transform raw data into actionable insights with our comprehensive Data Science program. Learn Python programming, statistical analysis, machine learning, and deep learning. Work with real-world datasets, build predictive models, and create stunning data visualizations. This program is designed to create industry-ready data scientists.",
        "prerequisites": [
            "Basic mathematics (algebra, statistics)",
            "Logical thinking skills",
        ],
        "learning_outcomes": [
            "Manipulate and analyze data using Pandas and NumPy",
            "Build interactive visualizations with Matplotlib, Seaborn, and Plotly",
            "Apply machine learning algorithms to solve real-world problems",
            "Develop deep learning models with TensorFlow and PyTorch",
            "Deploy data science models to production",
        ],
        "career_opportunities": [
            "Data Scientist",
            "Machine Learning Engineer",
            "Data Analyst",
            "AI Research Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Python for Data Science",
                "duration_weeks": 5,
                "topics": [
                    "Python Refresher: Data Types, Functions, OOP",
                    "NumPy: Arrays, Vectorization, Broadcasting, Linear Algebra",
                    "Pandas: Series, DataFrames, GroupBy, Merge, Reshape",
                    "Data Cleaning: Handling Missing Values, Outliers, Duplicates",
                    "Data Wrangling: Pivot Tables, MultiIndex, String Operations",
                    "Exploratory Data Analysis (EDA) Techniques",
                    "Project: Exploratory Analysis of Real-World Dataset",
                ],
            },
            {
                "title": "Module 2: Statistics & Probability",
                "duration_weeks": 5,
                "topics": [
                    "Descriptive Statistics: Mean, Median, Mode, Variance, Standard Deviation",
                    "Probability Theory: Distributions (Normal, Binomial, Poisson)",
                    "Inferential Statistics: Confidence Intervals, Hypothesis Testing",
                    "Correlation & Covariance Analysis",
                    "Bayesian Statistics: Bayes Theorem, Naive Bayes",
                    "Statistical Tests: T-Test, Chi-Square, ANOVA",
                    "Feature Engineering: Scaling, Transformation, Encoding",
                ],
            },
            {
                "title": "Module 3: Data Visualization",
                "duration_weeks": 4,
                "topics": [
                    "Matplotlib: Figure, Axes, Subplots, Customization",
                    "Seaborn: Statistical Plots, Heatmaps, Pair Plots, FacetGrid",
                    "Plotly: Interactive Charts, Dashboards, Animations",
                    "Geographic Visualizations with Folium & Geopandas",
                    "Dashboard Creation with Dash/Streamlit",
                    "Storytelling with Data: Best Practices",
                    "Project: Interactive Data Dashboard",
                ],
            },
            {
                "title": "Module 4: Machine Learning Fundamentals",
                "duration_weeks": 6,
                "topics": [
                    "Supervised Learning: Linear Regression, Logistic Regression",
                    "Tree-Based Models: Decision Trees, Random Forest, XGBoost",
                    "Support Vector Machines (SVM): Kernels, Soft Margin",
                    "Unsupervised Learning: K-Means, Hierarchical Clustering, DBSCAN",
                    "Dimensionality Reduction: PCA, t-SNE, LDA",
                    "Model Evaluation: Cross-Validation, ROC Curves, Confusion Matrix",
                    "Hyperparameter Tuning: Grid Search, Random Search, Bayesian Optimization",
                    "Project: Predictive Modeling Challenge",
                ],
            },
            {
                "title": "Module 5: Deep Learning & Neural Networks",
                "duration_weeks": 6,
                "topics": [
                    "Neural Network Fundamentals: Perceptron, Activation Functions, Backpropagation",
                    "TensorFlow & Keras: Sequential API, Functional API",
                    "Convolutional Neural Networks (CNNs): Image Classification, Object Detection",
                    "Recurrent Neural Networks (RNNs): LSTM, GRU, Time Series",
                    "Natural Language Processing: Tokenization, Word Embeddings, Transformers",
                    "Transfer Learning & Fine-Tuning",
                    "Generative AI: GANs, Autoencoders",
                    "Project: Image Classification or NLP Application",
                ],
            },
            {
                "title": "Module 6: MLOps & Capstone Project",
                "duration_weeks": 4,
                "topics": [
                    "Model Deployment: Flask/FastAPI, Docker, AWS SageMaker",
                    "ML Pipelines: Feature Stores, Model Registry",
                    "Experiment Tracking with MLflow",
                    "Model Monitoring & Drift Detection",
                    "Big Data Tools: Spark, Dask",
                    "SQL for Data Scientists",
                    "Capstone Project: End-to-End Data Science Solution",
                ],
            },
        ],
    },
    {
        "code": "DA",
        "name": "Data Analytics (Excel+SQL+BI)",
        "duration": 6,
        "fee": 35000,
        "description": "Kickstart your career in data analytics with this practical, hands-on program. Master Microsoft Excel (advanced formulas, pivot tables, macros), SQL (queries, database design), and Business Intelligence tools (Power BI, Tableau). Learn to transform raw data into actionable business insights and create professional dashboards.",
        "prerequisites": ["Basic computer literacy", "High school mathematics"],
        "learning_outcomes": [
            "Perform advanced data analysis using Excel functions and tools",
            "Write complex SQL queries to extract and manipulate data",
            "Create interactive dashboards with Power BI and Tableau",
            "Apply statistical analysis to business problems",
            "Present data-driven recommendations to stakeholders",
        ],
        "career_opportunities": [
            "Data Analyst",
            "Business Analyst",
            "BI Developer",
            "Reporting Analyst",
        ],
        "modules": [
            {
                "title": "Module 1: Advanced Excel Mastery",
                "duration_weeks": 5,
                "topics": [
                    "Excel Fundamentals: Formatting, Conditional Formatting, Data Validation",
                    "Advanced Formulas: VLOOKUP, INDEX-MATCH, XLOOKUP, INDIRECT",
                    "Logical Functions: IF, IFS, SWITCH, AND, OR, NOT",
                    "Text Functions: LEFT, RIGHT, MID, CONCATENATE, TEXTJOIN",
                    "Date & Time Functions: DATEDIF, WORKDAY, NETWORKDAYS",
                    "Statistical Functions: AVERAGEIF, COUNTIF, SUMIFS",
                    "Pivot Tables & Pivot Charts: Grouping, Slicers, Calculated Fields",
                    "Power Query: Data Transformation, Merging Queries",
                    "Macros & VBA: Recording, Editing, Automation",
                    "Project: Sales Dashboard in Excel",
                ],
            },
            {
                "title": "Module 2: SQL & Database Management",
                "duration_weeks": 5,
                "topics": [
                    "Database Fundamentals: Tables, Relationships, Normalization",
                    "SQL Basics: SELECT, WHERE, ORDER BY, LIMIT",
                    "Joins: INNER, LEFT, RIGHT, FULL OUTER, CROSS JOIN",
                    "Subqueries: Correlated vs Non-Correlated",
                    "Aggregation: GROUP BY, HAVING, Window Functions",
                    "CTEs (Common Table Expressions) & Recursive Queries",
                    "Views, Indexes, and Stored Procedures",
                    "Data Cleaning with SQL",
                    "Project: Business Database & Analytical Queries",
                ],
            },
            {
                "title": "Module 3: Power BI & Data Visualization",
                "duration_weeks": 4,
                "topics": [
                    "Power BI Desktop: Interface, Data Sources, Query Editor",
                    "Data Modeling: Relationships, Calculated Columns, Measures (DAX)",
                    "DAX Functions: CALCULATE, FILTER, ALL, RELATED, SUMX",
                    "Visualizations: Charts, Maps, Tables, Matrices, KPIs",
                    "Interactive Reports: Slicers, Drill-through, Bookmarks",
                    "Power BI Service: Publishing, Sharing, Workspaces",
                    "Project: Executive Sales Dashboard",
                ],
            },
            {
                "title": "Module 4: Business Analytics & Capstone",
                "duration_weeks": 4,
                "topics": [
                    "Introduction to Tableau: Worksheets, Dashboards, Stories",
                    "Statistical Analysis for Business: Regression, Forecasting",
                    "A/B Testing & Experimentation Design",
                    "Data Storytelling: Presentations & Communication",
                    "Case Studies: Real Business Problems",
                    "Capstone Project: End-to-End Analytics Solution",
                ],
            },
        ],
    },
    {
        "code": "CYBER",
        "name": "Cyber Security & Ethical Hack",
        "duration": 10,
        "fee": 60000,
        "description": "Protect the digital world with our comprehensive Cyber Security & Ethical Hacking program. Learn network security, penetration testing, vulnerability assessment, cryptography, and incident response. Gain hands-on experience with industry-standard tools like Kali Linux, Metasploit, and Wireshark in our dedicated lab environment.",
        "prerequisites": [
            "Basic networking knowledge",
            "Familiarity with Linux command line",
        ],
        "learning_outcomes": [
            "Conduct penetration tests on networks and web applications",
            "Identify and exploit vulnerabilities ethically",
            "Implement security measures to protect infrastructure",
            "Perform digital forensics and incident response",
            "Prepare for industry certifications (CEH, CompTIA Security+)",
        ],
        "career_opportunities": [
            "Ethical Hacker",
            "Security Analyst",
            "Penetration Tester",
            "Security Consultant",
            "CISO",
        ],
        "modules": [
            {
                "title": "Module 1: Networking & Security Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "Network Fundamentals: OSI Model, TCP/IP, Subnetting, VLANs",
                    "Network Protocols: HTTP, HTTPS, DNS, DHCP, ARP, ICMP",
                    "Firewalls: Types, Rules, Configuration (iptables, pfSense)",
                    "VPNs: Site-to-Site, Remote Access, WireGuard, OpenVPN",
                    "Linux Essentials: Command Line, File System, Permissions",
                    "Kali Linux: Installation, Tools Overview, Environment Setup",
                    "Virtualization: VMware, VirtualBox, Lab Network Setup",
                ],
            },
            {
                "title": "Module 2: Ethical Hacking & Reconnaissance",
                "duration_weeks": 5,
                "topics": [
                    "Footprinting & Reconnaissance: Passive Information Gathering",
                    "OSINT: Google Dorking, Shodan, Maltego, theHarvester",
                    "Network Scanning: Nmap, Masscan, Zenmap",
                    "Enumeration: NetBIOS, SNMP, LDAP, SMTP, DNS Enumeration",
                    "Vulnerability Scanning: Nessus, OpenVAS, Nikto",
                    "Social Engineering: Phishing, Pretexting, Physical Security",
                    "Practice: Complete Reconnaissance on a Target Network",
                ],
            },
            {
                "title": "Module 3: System Hacking & Exploitation",
                "duration_weeks": 5,
                "topics": [
                    "Password Cracking: John the Ripper, Hashcat, Hydra",
                    "Metasploit Framework: Modules, Payloads, Exploit Development",
                    "Buffer Overflow: Stack Overflow, SEH, ASLR Bypass",
                    "Windows Exploitation: Privilege Escalation, Persistence",
                    "Linux Exploitation: Kernel Exploits, SUID, Cron Jobs",
                    "Web Application Hacking: SQL Injection, XSS, CSRF, SSRF",
                    "Wireless Attacks: WPA2 Cracking, Evil Twin, Deauth Attack",
                    "Practice: Capture The Flag (CTF) Challenges",
                ],
            },
            {
                "title": "Module 4: Digital Forensics & Incident Response",
                "duration_weeks": 5,
                "topics": [
                    "Digital Forensics Methodology: Identification, Preservation, Analysis",
                    "Disk Forensics: EnCase, FTK Imager, Autopsy, Sleuth Kit",
                    "Memory Forensics: Volatility, Dump Analysis",
                    "Network Forensics: Wireshark, tcpdump, Network Miner",
                    "Incident Response Lifecycle: Preparation, Detection, Containment, Eradication",
                    "Malware Analysis: Static, Dynamic, Reverse Engineering Basics",
                    "Cyber Law & Compliance: GDPR, IT Act, ISO 27001",
                ],
            },
            {
                "title": "Module 5: Advanced Security & Capstone",
                "duration_weeks": 4,
                "topics": [
                    "Cryptography: Symmetric, Asymmetric, Hashing, PKI",
                    "Cloud Security: AWS, Azure Security Best Practices",
                    "DevSecOps: Integrating Security in CI/CD Pipeline",
                    "SIEM: Splunk, ELK Stack, Security Monitoring",
                    "Bug Bounty: Methodology, Platforms (HackerOne, Bugcrowd)",
                    "Certification Preparation: CEH, CompTIA Security+, OSCP",
                    "Capstone Project: Full Penetration Test Report",
                ],
            },
        ],
    },
    {
        "code": "AIML",
        "name": "AI & Machine Learning",
        "duration": 12,
        "fee": 75000,
        "description": "Dive deep into the world of Artificial Intelligence and Machine Learning. This comprehensive program covers everything from classical ML algorithms to cutting-edge deep learning, natural language processing, computer vision, and generative AI. Work with TensorFlow, PyTorch, and Hugging Face to build intelligent systems that solve real-world problems.",
        "prerequisites": [
            "Python programming experience",
            "Linear algebra & calculus basics",
            "Statistics fundamentals",
        ],
        "learning_outcomes": [
            "Build and deploy machine learning models end-to-end",
            "Develop deep neural networks for complex tasks",
            "Implement NLP pipelines for text processing and generation",
            "Create computer vision applications for image and video analysis",
            "Work with transformer models and large language models",
        ],
        "career_opportunities": [
            "Machine Learning Engineer",
            "AI Research Scientist",
            "Deep Learning Engineer",
            "Computer Vision Engineer",
            "NLP Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Mathematics for Machine Learning",
                "duration_weeks": 5,
                "topics": [
                    "Linear Algebra: Vectors, Matrices, Eigenvalues, SVD",
                    "Calculus: Derivatives, Gradients, Chain Rule, Partial Derivatives",
                    "Probability & Statistics: Distributions, Bayes Theorem, MLE",
                    "Optimization: Gradient Descent, SGD, Adam, RMSprop",
                    "Information Theory: Entropy, KL Divergence, Cross-Entropy",
                    "Python Review: NumPy, SciPy, Matplotlib for ML",
                ],
            },
            {
                "title": "Module 2: Classical Machine Learning",
                "duration_weeks": 6,
                "topics": [
                    "Supervised Learning: Linear Regression, Ridge, Lasso",
                    "Classification: Logistic Regression, Decision Trees, Random Forest",
                    "Support Vector Machines: Kernels, Soft Margin, SVR",
                    "Ensemble Methods: Bagging, Boosting, AdaBoost, XGBoost, LightGBM",
                    "Unsupervised Learning: K-Means, DBSCAN, Hierarchical Clustering",
                    "Dimensionality Reduction: PCA, t-SNE, UMAP",
                    "Model Evaluation: Cross-Validation, Grid Search, Metrics",
                    "Feature Engineering & Selection Techniques",
                    "Project: ML Model for Tabular Data",
                ],
            },
            {
                "title": "Module 3: Neural Networks & Deep Learning",
                "duration_weeks": 6,
                "topics": [
                    "Neural Network Architecture: Layers, Activation Functions, Loss Functions",
                    "Backpropagation: Chain Rule, Gradient Computation, Automatic Differentiation",
                    "TensorFlow 2.x: Keras API, Custom Training Loops, tf.data",
                    "PyTorch: Tensors, Autograd, nn.Module, DataLoader",
                    "Regularization: Dropout, Batch Normalization, L1/L2",
                    "Advanced Architectures: ResNet, Inception, EfficientNet",
                    "Transfer Learning & Fine-Tuning Pre-trained Models",
                    "Hyperparameter Optimization: Optuna, Keras Tuner",
                    "Project: Image Classification with CNN",
                ],
            },
            {
                "title": "Module 4: Natural Language Processing",
                "duration_weeks": 5,
                "topics": [
                    "Text Processing: Tokenization, Stemming, Lemmatization, Stop Words",
                    "Word Embeddings: Word2Vec, GloVe, FastText",
                    "RNNs, LSTMs, GRUs for Sequence Modeling",
                    "Attention Mechanism & Transformer Architecture",
                    "BERT, GPT, T5: Pre-trained Language Models",
                    "Hugging Face: Transformers Library, Pipeline, Fine-tuning",
                    "NLP Tasks: Text Classification, NER, Question Answering, Summarization",
                    "Project: Sentiment Analysis & Text Generation System",
                ],
            },
            {
                "title": "Module 5: Computer Vision",
                "duration_weeks": 5,
                "topics": [
                    "Image Processing: OpenCV, Filtering, Edge Detection",
                    "CNN Architectures: AlexNet, VGG, ResNet, Inception",
                    "Object Detection: YOLO, SSD, Faster R-CNN",
                    "Image Segmentation: U-Net, Mask R-CNN",
                    "Generative Models: GANs, VAEs, Diffusion Models",
                    "Vision Transformers (ViT)",
                    "Video Analysis: Action Recognition, Object Tracking",
                    "Project: Real-Time Object Detection System",
                ],
            },
            {
                "title": "Module 6: MLOps & Capstone Project",
                "duration_weeks": 5,
                "topics": [
                    "ML Pipeline: Data Versioning (DVC), Feature Store",
                    "Experiment Tracking: MLflow, Weights & Biases",
                    "Model Deployment: FastAPI, Docker, Kubernetes",
                    "Cloud AI Services: AWS SageMaker, GCP AI Platform",
                    "Model Monitoring: Drift Detection, Performance Metrics",
                    "Responsible AI: Fairness, Bias, Explainability (SHAP, LIME)",
                    "Generative AI: Prompt Engineering, LangChain, RAG",
                    "Capstone Project: End-to-End AI Solution",
                ],
            },
        ],
    },
    {
        "code": "CLOUD",
        "name": "Cloud Computing (AWS+Azure)",
        "duration": 8,
        "fee": 50000,
        "description": "Master cloud computing with hands-on training on AWS and Microsoft Azure. Learn to design, deploy, and manage scalable cloud infrastructure. Cover core services, networking, security, storage, compute, serverless computing, containers, and DevOps practices. Prepare for industry certifications like AWS Solutions Architect and Azure Administrator.",
        "prerequisites": [
            "Basic IT infrastructure knowledge",
            "Networking fundamentals",
        ],
        "learning_outcomes": [
            "Design and implement cloud architectures on AWS and Azure",
            "Configure virtual networks, security groups, and IAM policies",
            "Deploy and manage containers with Docker and Kubernetes",
            "Implement CI/CD pipelines for cloud applications",
            "Optimize cloud costs and implement best practices",
        ],
        "career_opportunities": [
            "Cloud Architect",
            "DevOps Engineer",
            "Cloud Engineer",
            "Site Reliability Engineer (SRE)",
        ],
        "modules": [
            {
                "title": "Module 1: Cloud Computing Fundamentals",
                "duration_weeks": 4,
                "topics": [
                    "Cloud Computing Models: IaaS, PaaS, SaaS, FaaS",
                    "Deployment Models: Public, Private, Hybrid, Multi-Cloud",
                    "AWS Global Infrastructure: Regions, AZs, Edge Locations",
                    "Azure Global Infrastructure: Regions, Availability Zones",
                    "AWS Free Tier & Account Setup",
                    "Azure Free Account & Portal Overview",
                    "Billing & Cost Management: AWS Cost Explorer, Azure Cost Management",
                    "Cloud Security Shared Responsibility Model",
                ],
            },
            {
                "title": "Module 2: Compute & Storage Services",
                "duration_weeks": 5,
                "topics": [
                    "AWS EC2: Instance Types, AMIs, Security Groups, EBS",
                    "Azure VMs: Sizes, Disks, Availability Sets",
                    "AWS S3: Buckets, Objects, Versioning, Lifecycle Policies",
                    "Azure Blob Storage: Containers, Access Tiers, Replication",
                    "AWS EBS & EFS: Block vs File Storage",
                    "Azure Files & Azure Disk Storage",
                    "AWS RDS: Databases, Multi-AZ, Read Replicas",
                    "Azure SQL Database: Elastic Pools, Managed Instance",
                    "AWS Lambda: Serverless Functions, Triggers",
                    "Azure Functions: Triggers, Bindings, Durable Functions",
                ],
            },
            {
                "title": "Module 3: Networking & Security",
                "duration_weeks": 5,
                "topics": [
                    "AWS VPC: Subnets, Route Tables, NAT Gateways, Internet Gateways",
                    "Azure VNet: Subnets, Peering, VPN Gateway",
                    "AWS IAM: Users, Groups, Roles, Policies, MFA",
                    "Azure AD: Identity, RBAC, Managed Identities",
                    "AWS ELB & ALB: Load Balancers, Target Groups, Health Checks",
                    "Azure Load Balancer: Public, Internal, Application Gateway",
                    "AWS CloudFront: CDN, Behaviors, Origin Access",
                    "Azure CDN: Profiles, Endpoints, Rules Engine",
                    "AWS WAF & Shield: Web ACLs, DDoS Protection",
                    "Azure Firewall & DDoS Protection",
                ],
            },
            {
                "title": "Module 4: Containers & DevOps",
                "duration_weeks": 5,
                "topics": [
                    "Docker: Images, Containers, Dockerfile, Docker Compose",
                    "Amazon ECR: Container Registry, Image Scanning",
                    "Azure Container Registry: Repositories, Tasks",
                    "Amazon ECS: Task Definitions, Services, Fargate",
                    "Azure Container Instances & AKS",
                    "Kubernetes: Pods, Deployments, Services, ConfigMaps",
                    "Infrastructure as Code: AWS CloudFormation, Terraform",
                    "CI/CD: AWS CodePipeline, Azure DevOps Pipelines",
                    "Configuration Management: Ansible, AWS Systems Manager",
                    "Monitoring: CloudWatch, Azure Monitor, Prometheus, Grafana",
                ],
            },
            {
                "title": "Module 5: Advanced Topics & Certification",
                "duration_weeks": 3,
                "topics": [
                    "AWS Lambda Advanced: Layers, VPC Integration, Step Functions",
                    "Azure Logic Apps & Power Automate",
                    "API Gateway: AWS API Gateway, Azure API Management",
                    "Disaster Recovery: Backup, Multi-Region, RTO/RPO",
                    "Cost Optimization: Reserved Instances, Spot Instances, Savings Plans",
                    "AWS Well-Architected Framework",
                    "Azure Well-Architected Framework",
                    "Certification Preparation: AWS SAA, Azure AZ-104",
                    "Capstone Project: Multi-Tier Cloud Architecture Implementation",
                ],
            },
        ],
    },
    {
        "code": "MOB",
        "name": "Mobile App Dev (Flutter)",
        "duration": 8,
        "fee": 50000,
        "description": "Build beautiful, natively compiled mobile apps for iOS and Android from a single codebase using Flutter and Dart. This comprehensive program covers everything from widget fundamentals to state management, animations, API integration, and app store deployment. Create production-ready apps with Firebase backend and publish them to Google Play and App Store.",
        "prerequisites": [
            "Basic programming concepts",
            "Familiarity with object-oriented programming",
        ],
        "learning_outcomes": [
            "Build cross-platform mobile apps with Flutter",
            "Implement state management using Provider, Riverpod, and Bloc",
            "Integrate REST APIs, Firebase, and local databases",
            "Create smooth animations and custom UI components",
            "Publish apps to Google Play Store and Apple App Store",
        ],
        "career_opportunities": [
            "Flutter Developer",
            "Mobile App Developer",
            "Cross-Platform Developer",
            "React Native Developer",
        ],
        "modules": [
            {
                "title": "Module 1: Dart Programming Language",
                "duration_weeks": 4,
                "topics": [
                    "Dart Basics: Variables, Data Types, Operators, Control Flow",
                    "Functions: Parameters, Arrow Functions, Anonymous Functions",
                    "Object-Oriented Dart: Classes, Inheritance, Mixins, Abstract Classes",
                    "Collections: List, Set, Map, Iterables",
                    "Asynchronous Dart: Futures, Streams, Async/Await",
                    "Error Handling & Exceptions",
                    "Dart Packages: pub.dev, Dependencies, Versioning",
                    "Project: Dart Command-Line Applications",
                ],
            },
            {
                "title": "Module 2: Flutter Widgets & UI",
                "duration_weeks": 5,
                "topics": [
                    "Flutter Architecture: Widget Tree, Element Tree, Render Tree",
                    "Layout Widgets: Container, Row, Column, Stack, Expanded, Flexible",
                    "Material Design: AppBar, Drawer, BottomNavigation, Cards",
                    "Input Widgets: TextField, Form, Button, Dropdown, DatePicker",
                    "Navigation: Named Routes, Navigator 2.0, GoRouter",
                    "Theming: ThemeData, Custom Themes, Dark Mode",
                    "Responsive Design: MediaQuery, LayoutBuilder, OrientationBuilder",
                    "Custom Painting & Custom Widgets",
                    "Project: Complete UI Design for a Social Media App",
                ],
            },
            {
                "title": "Module 3: State Management",
                "duration_weeks": 3,
                "topics": [
                    "setState & InheritedWidget (Basic State Management)",
                    "Provider: ChangeNotifier, MultiProvider, Consumer",
                    "Riverpod: Providers, Ref, AsyncNotifier",
                    "Bloc/Cubit: Events, States, BlocProvider, BlocBuilder",
                    "State Management Comparison & Best Practices",
                    "Project: Refactor App with Proper State Management",
                ],
            },
            {
                "title": "Module 4: Backend Integration & Data Persistence",
                "duration_weeks": 5,
                "topics": [
                    "HTTP & REST APIs: http package, Dio, JSON Serialization",
                    "Firebase Integration: Firebase Auth, Cloud Firestore, Storage",
                    "Local Storage: SharedPreferences, SQLite (sqflite), Hive",
                    "GraphQL Integration with Flutter",
                    "WebSockets: Real-Time Communication",
                    "Authentication: Firebase Auth, Google Sign-In, Apple Sign-In",
                    "Push Notifications: Firebase Cloud Messaging (FCM)",
                    "Project: Full-Stack Mobile App with Firebase Backend",
                ],
            },
            {
                "title": "Module 5: Animations & Deployment",
                "duration_weeks": 3,
                "topics": [
                    "Implicit Animations: AnimatedContainer, AnimatedOpacity, TweenAnimationBuilder",
                    "Explicit Animations: AnimationController, Tween, Curve",
                    "Hero Animations & Staggered Animations",
                    "Custom Painter & Animated Widgets",
                    "App Polish: Splash Screen, Onboarding, Error Handling",
                    "Testing: Unit Tests, Widget Tests, Integration Tests",
                    "App Store Publishing: Google Play Console, App Store Connect",
                    "Capstone Project: Production-Ready Mobile Application",
                ],
            },
        ],
    },
    {
        "code": "DBMS",
        "name": "Database Management (SQL+NoSQL)",
        "duration": 6,
        "fee": 35000,
        "description": "Become a database expert with comprehensive training in both SQL and NoSQL technologies. Learn to design, implement, and optimize database systems using MySQL, PostgreSQL, MongoDB, and Redis. Master database administration, performance tuning, data modeling, and security. This course prepares you for database roles across all types of organizations.",
        "prerequisites": ["Basic computer literacy", "Logical thinking skills"],
        "learning_outcomes": [
            "Design normalized relational database schemas",
            "Write complex SQL queries, stored procedures, and triggers",
            "Work with MongoDB for document-based data storage",
            "Implement caching solutions with Redis",
            "Optimize database performance and ensure data security",
        ],
        "career_opportunities": [
            "Database Administrator",
            "Database Developer",
            "Data Engineer",
            "Backend Developer",
            "Analytics Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Relational Database Design",
                "duration_weeks": 4,
                "topics": [
                    "Database Concepts: Tables, Relationships, Keys",
                    "Entity-Relationship (ER) Modeling: Entities, Attributes, Relationships",
                    "Normalization: 1NF, 2NF, 3NF, BCNF, 4NF",
                    "Denormalization: When and Why",
                    "Data Types: Numeric, String, Date/Time, Binary",
                    "Constraints: Primary Key, Foreign Key, Unique, Check, Default",
                    "Indexes: B-Tree, Hash, Composite, Full-Text",
                    "Database Design Tools: MySQL Workbench, dbdiagram.io",
                ],
            },
            {
                "title": "Module 2: Advanced SQL & PostgreSQL",
                "duration_weeks": 5,
                "topics": [
                    "SQL Fundamentals: SELECT, INSERT, UPDATE, DELETE",
                    "Joins: INNER, LEFT, RIGHT, FULL, CROSS, SELF",
                    "Subqueries: Scalar, Row, Table, Correlated, EXISTS",
                    "Set Operations: UNION, INTERSECT, EXCEPT",
                    "Aggregate Functions: COUNT, SUM, AVG, MIN, MAX",
                    "Window Functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD",
                    "CTEs & Recursive Queries",
                    "Views, Materialized Views, and Triggers",
                    "Stored Procedures & Functions (PL/pgSQL)",
                    "Transactions: ACID, Isolation Levels, Locks",
                    "Project: E-Commerce Database with Advanced Queries",
                ],
            },
            {
                "title": "Module 3: NoSQL Databases - MongoDB",
                "duration_weeks": 4,
                "topics": [
                    "NoSQL Concepts: Document Stores, Key-Value, Column Family, Graph",
                    "MongoDB: Documents, Collections, Databases",
                    "CRUD Operations: insert, find, update, delete",
                    "Aggregation Pipeline: $match, $group, $sort, $lookup, $unwind",
                    "Indexing: Single Field, Compound, Text, Geospatial",
                    "Schema Design: Embedding vs Referencing, Patterns",
                    "MongoDB Atlas: Cloud Cluster, Backup, Monitoring",
                    "Mongoose ODM for Node.js",
                    "Replication & Sharding Concepts",
                    "Project: Social Media Data Model in MongoDB",
                ],
            },
            {
                "title": "Module 4: Redis & Performance Optimization",
                "duration_weeks": 3,
                "topics": [
                    "Redis: Data Types (String, Hash, List, Set, Sorted Set)",
                    "Redis: Caching Strategies, TTL, Eviction Policies",
                    "Redis: Pub/Sub, Transactions, Lua Scripting",
                    "Redis: Persistence (RDB, AOF), High Availability (Sentinel)",
                    "Database Performance Tuning: Query Optimization, EXPLAIN",
                    "Connection Pooling & Configuration Tuning",
                    "Backup & Recovery Strategies",
                    "Monitoring: pg_stat_statements, MongoDB Atlas Monitoring",
                ],
            },
            {
                "title": "Module 5: Database Security & Administration",
                "duration_weeks": 2,
                "topics": [
                    "Authentication & Authorization: Roles, Privileges",
                    "Encryption: TDE, SSL/TLS, Column-Level Encryption",
                    "SQL Injection Prevention & Security Best Practices",
                    "Auditing & Compliance (GDPR, HIPAA)",
                    "Database Migration: Tools, Strategies, Zero Downtime",
                    "Capstone Project: Complete Database Solution",
                ],
            },
        ],
    },
    {
        "code": "UIUX",
        "name": "UI/UX Design & Prototyping",
        "duration": 6,
        "fee": 40000,
        "description": "Design exceptional digital experiences with our UI/UX Design program. Learn user research, information architecture, wireframing, visual design, and prototyping using industry-standard tools like Figma, Adobe XD, and Sketch. Master design thinking methodology, create stunning user interfaces, and build interactive prototypes ready for development handoff.",
        "prerequisites": [
            "No prior design experience needed",
            "Creative thinking and attention to detail",
        ],
        "learning_outcomes": [
            "Conduct user research and translate insights into design decisions",
            "Create wireframes, mockups, and interactive prototypes in Figma",
            "Apply design principles, color theory, and typography",
            "Design for accessibility and inclusive experiences",
            "Build a professional design portfolio with real projects",
        ],
        "career_opportunities": [
            "UI/UX Designer",
            "Product Designer",
            "Interaction Designer",
            "UX Researcher",
            "Visual Designer",
        ],
        "modules": [
            {
                "title": "Module 1: Design Thinking & User Research",
                "duration_weeks": 4,
                "topics": [
                    "Design Thinking Process: Empathize, Define, Ideate, Prototype, Test",
                    "User Research Methods: Surveys, Interviews, Observations",
                    "User Personas: Creating Empathy Maps & User Profiles",
                    "User Journey Mapping & Experience Mapping",
                    "Problem Statements & Hypothesis Formulation",
                    "Competitive Analysis: SWOT Analysis, Feature Comparison",
                    "Information Architecture: Card Sorting, Sitemaps, User Flows",
                    "Project: Research & Define a Mobile App Concept",
                ],
            },
            {
                "title": "Module 2: Visual Design Principles",
                "duration_weeks": 4,
                "topics": [
                    "Design Fundamentals: Balance, Contrast, Hierarchy, Unity",
                    "Color Theory: Color Wheel, Harmonies, Psychology, Accessibility",
                    "Typography: Typefaces, Font Pairing, Readability, Hierarchy",
                    "Layout & Composition: Grid Systems, White Space, Visual Rhythm",
                    "Iconography: Icon Design Principles, Custom vs Library Icons",
                    "Imagery & Photography: Selection, Cropping, Editing",
                    "Design Systems: Components, Patterns, Style Guides",
                    "Project: Design System Component Library in Figma",
                ],
            },
            {
                "title": "Module 3: Figma Mastery & Prototyping",
                "duration_weeks": 5,
                "topics": [
                    "Figma Fundamentals: Frames, Shapes, Pen Tool, Boolean Operations",
                    "Components & Variants: Create, Manage, Document",
                    "Auto Layout: Padding, Spacing, Responsive Design",
                    "Constraints & Grids: Responsive Layouts",
                    "Plugins: Content Generators, Accessibility Checkers, Icons",
                    "Interactive Prototyping: Connections, Animations, Overlays",
                    "Design Handoff: Developer Mode, Export, Specs",
                    "Figma Collaboration: Libraries, Comments, Version History",
                    "Project: High-Fidelity Mobile App Prototype",
                ],
            },
            {
                "title": "Module 4: Interaction Design & Micro-interactions",
                "duration_weeks": 3,
                "topics": [
                    "Interaction Design Principles: Fitts's Law, Hick's Law, Jakob's Law",
                    "Micro-interactions: Triggers, Rules, Feedback, Loops",
                    "Motion Design: Easing, Transitions, Choreography",
                    "Gestalt Principles: Proximity, Similarity, Closure, Continuity",
                    "Mobile Gestures: Tap, Swipe, Pinch, Long Press",
                    "Accessibility: WCAG Guidelines, Screen Readers, Color Contrast",
                    "Project: Add Interactions to App Prototype",
                ],
            },
            {
                "title": "Module 5: Portfolio & Industry Preparation",
                "duration_weeks": 2,
                "topics": [
                    "UX Writing: Microcopy, Tone, Voice",
                    "Design Critique: Giving & Receiving Feedback",
                    "Portfolio Development: Case Study Structure, Presentation",
                    "Resume & LinkedIn Optimization for Designers",
                    "Freelancing: Client Management, Pricing, Contracts",
                    "Capstone Project: Complete Product Design Case Study",
                ],
            },
        ],
    },
]
