# Courses 9-11

_courses_3 = [
    {
        "code": "MOB",
        "name": "Mobile App Dev (Flutter)",
        "duration": 8,
        "fee": 50000,
        "description": "Build beautiful, natively compiled mobile apps for iOS and Android from a single codebase using Flutter and Dart. This comprehensive program covers everything from widget fundamentals to state management, animations, API integration, and app store deployment. Create production-ready apps with Firebase backend and publish them to Google Play and App Store.",
        "prerequisites": [
            "Basic programming concepts",
            "Familiarity with object-oriented programming",
        ],
        "learning_outcomes": [
            "Build cross-platform mobile apps with Flutter",
            "Implement state management using Provider, Riverpod, and Bloc",
            "Integrate REST APIs, Firebase, and local databases",
            "Create smooth animations and custom UI components",
            "Publish apps to Google Play Store and Apple App Store",
        ],
        "career_opportunities": [
            "Flutter Developer",
            "Mobile App Developer",
            "Cross-Platform Developer",
            "React Native Developer",
        ],
        "modules": [
            {
                "title": "Module 1: Dart Programming Language",
                "duration_weeks": 4,
                "topics": [
                    "Dart Basics: Variables, Data Types, Operators, Control Flow",
                    "Functions: Parameters, Arrow Functions, Anonymous Functions",
                    "Object-Oriented Dart: Classes, Inheritance, Mixins, Abstract Classes",
                    "Collections: List, Set, Map, Iterables",
                    "Asynchronous Dart: Futures, Streams, Async/Await",
                    "Error Handling & Exceptions",
                    "Dart Packages: pub.dev, Dependencies, Versioning",
                    "Project: Dart Command-Line Applications",
                ],
            },
            {
                "title": "Module 2: Flutter Widgets & UI",
                "duration_weeks": 5,
                "topics": [
                    "Flutter Architecture: Widget Tree, Element Tree, Render Tree",
                    "Layout Widgets: Container, Row, Column, Stack, Expanded, Flexible",
                    "Material Design: AppBar, Drawer, BottomNavigation, Cards",
                    "Input Widgets: TextField, Form, Button, Dropdown, DatePicker",
                    "Navigation: Named Routes, Navigator 2.0, GoRouter",
                    "Theming: ThemeData, Custom Themes, Dark Mode",
                    "Responsive Design: MediaQuery, LayoutBuilder, OrientationBuilder",
                    "Custom Painting & Custom Widgets",
                    "Project: Complete UI Design for a Social Media App",
                ],
            },
            {
                "title": "Module 3: State Management",
                "duration_weeks": 3,
                "topics": [
                    "setState & InheritedWidget (Basic State Management)",
                    "Provider: ChangeNotifier, MultiProvider, Consumer",
                    "Riverpod: Providers, Ref, AsyncNotifier",
                    "Bloc/Cubit: Events, States, BlocProvider, BlocBuilder",
                    "State Management Comparison & Best Practices",
                    "Project: Refactor App with Proper State Management",
                ],
            },
            {
                "title": "Module 4: Backend Integration & Data Persistence",
                "duration_weeks": 5,
                "topics": [
                    "HTTP & REST APIs: http package, Dio, JSON Serialization",
                    "Firebase Integration: Firebase Auth, Cloud Firestore, Storage",
                    "Local Storage: SharedPreferences, SQLite (sqflite), Hive",
                    "GraphQL Integration with Flutter",
                    "WebSockets: Real-Time Communication",
                    "Authentication: Firebase Auth, Google Sign-In, Apple Sign-In",
                    "Push Notifications: Firebase Cloud Messaging (FCM)",
                    "Project: Full-Stack Mobile App with Firebase Backend",
                ],
            },
            {
                "title": "Module 5: Animations & Deployment",
                "duration_weeks": 3,
                "topics": [
                    "Implicit Animations: AnimatedContainer, AnimatedOpacity, TweenAnimationBuilder",
                    "Explicit Animations: AnimationController, Tween, Curve",
                    "Hero Animations & Staggered Animations",
                    "Custom Painter & Animated Widgets",
                    "App Polish: Splash Screen, Onboarding, Error Handling",
                    "Testing: Unit Tests, Widget Tests, Integration Tests",
                    "App Store Publishing: Google Play Console, App Store Connect",
                    "Capstone Project: Production-Ready Mobile Application",
                ],
            },
        ],
    },
    {
        "code": "DBMS",
        "name": "Database Management (SQL+NoSQL)",
        "duration": 6,
        "fee": 35000,
        "description": "Become a database expert with comprehensive training in both SQL and NoSQL technologies. Learn to design, implement, and optimize database systems using MySQL, PostgreSQL, MongoDB, and Redis. Master database administration, performance tuning, data modeling, and security. This course prepares you for database roles across all types of organizations.",
        "prerequisites": ["Basic computer literacy", "Logical thinking skills"],
        "learning_outcomes": [
            "Design normalized relational database schemas",
            "Write complex SQL queries, stored procedures, and triggers",
            "Work with MongoDB for document-based data storage",
            "Implement caching solutions with Redis",
            "Optimize database performance and ensure data security",
        ],
        "career_opportunities": [
            "Database Administrator",
            "Database Developer",
            "Data Engineer",
            "Backend Developer",
            "Analytics Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Relational Database Design",
                "duration_weeks": 4,
                "topics": [
                    "Database Concepts: Tables, Relationships, Keys",
                    "Entity-Relationship (ER) Modeling: Entities, Attributes, Relationships",
                    "Normalization: 1NF, 2NF, 3NF, BCNF, 4NF",
                    "Denormalization: When and Why",
                    "Data Types: Numeric, String, Date/Time, Binary",
                    "Constraints: Primary Key, Foreign Key, Unique, Check, Default",
                    "Indexes: B-Tree, Hash, Composite, Full-Text",
                    "Database Design Tools: MySQL Workbench, dbdiagram.io",
                ],
            },
            {
                "title": "Module 2: Advanced SQL & PostgreSQL",
                "duration_weeks": 5,
                "topics": [
                    "SQL Fundamentals: SELECT, INSERT, UPDATE, DELETE",
                    "Joins: INNER, LEFT, RIGHT, FULL, CROSS, SELF",
                    "Subqueries: Scalar, Row, Table, Correlated, EXISTS",
                    "Set Operations: UNION, INTERSECT, EXCEPT",
                    "Aggregate Functions: COUNT, SUM, AVG, MIN, MAX",
                    "Window Functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD",
                    "CTEs & Recursive Queries",
                    "Views, Materialized Views, and Triggers",
                    "Stored Procedures & Functions (PL/pgSQL)",
                    "Transactions: ACID, Isolation Levels, Locks",
                    "Project: E-Commerce Database with Advanced Queries",
                ],
            },
            {
                "title": "Module 3: NoSQL Databases - MongoDB",
                "duration_weeks": 4,
                "topics": [
                    "NoSQL Concepts: Document Stores, Key-Value, Column Family, Graph",
                    "MongoDB: Documents, Collections, Databases",
                    "CRUD Operations: insert, find, update, delete",
                    "Aggregation Pipeline: $match, $group, $sort, $lookup, $unwind",
                    "Indexing: Single Field, Compound, Text, Geospatial",
                    "Schema Design: Embedding vs Referencing, Patterns",
                    "MongoDB Atlas: Cloud Cluster, Backup, Monitoring",
                    "Mongoose ODM for Node.js",
                    "Replication & Sharding Concepts",
                    "Project: Social Media Data Model in MongoDB",
                ],
            },
            {
                "title": "Module 4: Redis & Performance Optimization",
                "duration_weeks": 3,
                "topics": [
                    "Redis: Data Types (String, Hash, List, Set, Sorted Set)",
                    "Redis: Caching Strategies, TTL, Eviction Policies",
                    "Redis: Pub/Sub, Transactions, Lua Scripting",
                    "Redis: Persistence (RDB, AOF), High Availability (Sentinel)",
                    "Database Performance Tuning: Query Optimization, EXPLAIN",
                    "Connection Pooling & Configuration Tuning",
                    "Backup & Recovery Strategies",
                    "Monitoring: pg_stat_statements, MongoDB Atlas Monitoring",
                ],
            },
            {
                "title": "Module 5: Database Security & Administration",
                "duration_weeks": 2,
                "topics": [
                    "Authentication & Authorization: Roles, Privileges",
                    "Encryption: TDE, SSL/TLS, Column-Level Encryption",
                    "SQL Injection Prevention & Security Best Practices",
                    "Auditing & Compliance (GDPR, HIPAA)",
                    "Database Migration: Tools, Strategies, Zero Downtime",
                    "Capstone Project: Complete Database Solution",
                ],
            },
        ],
    },
    {
        "code": "UIUX",
        "name": "UI/UX Design & Prototyping",
        "duration": 6,
        "fee": 40000,
        "description": "Design exceptional digital experiences with our UI/UX Design program. Learn user research, information architecture, wireframing, visual design, and prototyping using industry-standard tools like Figma, Adobe XD, and Sketch. Master design thinking methodology, create stunning user interfaces, and build interactive prototypes ready for development handoff.",
        "prerequisites": [
            "No prior design experience needed",
            "Creative thinking and attention to detail",
        ],
        "learning_outcomes": [
            "Conduct user research and translate insights into design decisions",
            "Create wireframes, mockups, and interactive prototypes in Figma",
            "Apply design principles, color theory, and typography",
            "Design for accessibility and inclusive experiences",
            "Build a professional design portfolio with real projects",
        ],
        "career_opportunities": [
            "UI/UX Designer",
            "Product Designer",
            "Interaction Designer",
            "UX Researcher",
            "Visual Designer",
        ],
        "modules": [
            {
                "title": "Module 1: Design Thinking & User Research",
                "duration_weeks": 4,
                "topics": [
                    "Design Thinking Process: Empathize, Define, Ideate, Prototype, Test",
                    "User Research Methods: Surveys, Interviews, Observations",
                    "User Personas: Creating Empathy Maps & User Profiles",
                    "User Journey Mapping & Experience Mapping",
                    "Problem Statements & Hypothesis Formulation",
                    "Competitive Analysis: SWOT Analysis, Feature Comparison",
                    "Information Architecture: Card Sorting, Sitemaps, User Flows",
                    "Project: Research & Define a Mobile App Concept",
                ],
            },
            {
                "title": "Module 2: Visual Design Principles",
                "duration_weeks": 4,
                "topics": [
                    "Design Fundamentals: Balance, Contrast, Hierarchy, Unity",
                    "Color Theory: Color Wheel, Harmonies, Psychology, Accessibility",
                    "Typography: Typefaces, Font Pairing, Readability, Hierarchy",
                    "Layout & Composition: Grid Systems, White Space, Visual Rhythm",
                    "Iconography: Icon Design Principles, Custom vs Library Icons",
                    "Imagery & Photography: Selection, Cropping, Editing",
                    "Design Systems: Components, Patterns, Style Guides",
                    "Project: Design System Component Library in Figma",
                ],
            },
            {
                "title": "Module 3: Figma Mastery & Prototyping",
                "duration_weeks": 5,
                "topics": [
                    "Figma Fundamentals: Frames, Shapes, Pen Tool, Boolean Operations",
                    "Components & Variants: Create, Manage, Document",
                    "Auto Layout: Padding, Spacing, Responsive Design",
                    "Constraints & Grids: Responsive Layouts",
                    "Plugins: Content Generators, Accessibility Checkers, Icons",
                    "Interactive Prototyping: Connections, Animations, Overlays",
                    "Design Handoff: Developer Mode, Export, Specs",
                    "Figma Collaboration: Libraries, Comments, Version History",
                    "Project: High-Fidelity Mobile App Prototype",
                ],
            },
            {
                "title": "Module 4: Interaction Design & Micro-interactions",
                "duration_weeks": 3,
                "topics": [
                    "Interaction Design Principles: Fitts's Law, Hick's Law, Jakob's Law",
                    "Micro-interactions: Triggers, Rules, Feedback, Loops",
                    "Motion Design: Easing, Transitions, Choreography",
                    "Gestalt Principles: Proximity, Similarity, Closure, Continuity",
                    "Mobile Gestures: Tap, Swipe, Pinch, Long Press",
                    "Accessibility: WCAG Guidelines, Screen Readers, Color Contrast",
                    "Project: Add Interactions to App Prototype",
                ],
            },
            {
                "title": "Module 5: Portfolio & Industry Preparation",
                "duration_weeks": 2,
                "topics": [
                    "UX Writing: Microcopy, Tone, Voice",
                    "Design Critique: Giving & Receiving Feedback",
                    "Portfolio Development: Case Study Structure, Presentation",
                    "Resume & LinkedIn Optimization for Designers",
                    "Freelancing: Client Management, Pricing, Contracts",
                    "Capstone Project: Complete Product Design Case Study",
                ],
            },
        ],
    },
]
