# Courses 1-4

_courses_1 = [
    {
        "code": "WEBJ",
        "name": "Web Dev with Java (Full Stack)",
        "duration": 8,
        "fee": 45000,
        "description": "Become a complete Full Stack Java Developer with this intensive 8-month program. Learn front-end technologies (HTML, CSS, JavaScript) alongside Java back-end development using Spring Boot. Build enterprise-level web applications with RESTful APIs, microservices architecture, and modern databases.",
        "prerequisites": [
            "Basic computer literacy",
            "Logical thinking and problem-solving skills",
        ],
        "learning_outcomes": [
            "Build responsive web interfaces using HTML5, CSS3, and JavaScript",
            "Develop robust back-end services with Java and Spring Boot",
            "Design and implement RESTful APIs and microservices",
            "Work with both SQL and NoSQL databases",
            "Deploy full-stack applications to cloud platforms",
        ],
        "career_opportunities": [
            "Full Stack Java Developer",
            "Backend Developer",
            "Spring Boot Developer",
            "Enterprise Application Developer",
        ],
        "modules": [
            {
                "title": "Module 1: Front-End Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "HTML5: Semantic Elements, Forms, Media Elements, APIs",
                    "CSS3: Flexbox, Grid, Animations, Transitions, Responsive Design",
                    "JavaScript ES6+: Variables, Functions, Objects, Arrays, Promises, Async/Await",
                    "DOM Manipulation & Event Handling",
                    "Bootstrap 5: Grid System, Components, Utilities",
                    "Version Control with Git & GitHub",
                    "Project: Build a Complete Responsive Business Website",
                ],
            },
            {
                "title": "Module 2: Core Java Programming",
                "duration_weeks": 5,
                "topics": [
                    "Java Fundamentals: Data Types, Operators, Control Flow",
                    "OOP Concepts: Classes, Objects, Inheritance, Polymorphism, Abstraction, Encapsulation",
                    "Exception Handling & Custom Exceptions",
                    "Collections Framework: List, Set, Map, Queue",
                    "Generics, Lambda Expressions & Streams API",
                    "Multithreading & Concurrency",
                    "File I/O & Serialization",
                    "Java 8+ Features: Optional, Date/Time API, Functional Interfaces",
                ],
            },
            {
                "title": "Module 3: Advanced Java & Database",
                "duration_weeks": 5,
                "topics": [
                    "JDBC: Database Connectivity, Connection Pooling",
                    "SQL: DDL, DML, Joins, Subqueries, Indexes, Transactions",
                    "MySQL Workbench & Database Design",
                    "Hibernate ORM: Entities, Relationships, Caching, HQL",
                    "JPA (Java Persistence API)",
                    "Project: E-Commerce Database Design & Implementation",
                ],
            },
            {
                "title": "Module 4: Spring Boot & REST APIs",
                "duration_weeks": 5,
                "topics": [
                    "Spring Core: IoC, DI, Beans, Scopes",
                    "Spring Boot: Auto-Configuration, Starters, Actuator",
                    "REST API Design Principles & Best Practices",
                    "Spring MVC: Controllers, Services, Repositories",
                    "Spring Data JPA: Query Methods, Specifications, Auditing",
                    "Spring Security: Authentication, Authorization, JWT",
                    "API Documentation with Swagger/OpenAPI",
                    "Project: Build a Complete RESTful Backend",
                ],
            },
            {
                "title": "Module 5: Microservices & Deployment",
                "duration_weeks": 4,
                "topics": [
                    "Microservices Architecture Principles",
                    "Spring Cloud: Service Discovery, API Gateway, Config Server",
                    "Docker: Containers, Images, Docker Compose",
                    "Message Queues: RabbitMQ, Kafka",
                    "Unit Testing with JUnit 5 & Mockito",
                    "CI/CD Pipeline with Jenkins & GitHub Actions",
                    "Cloud Deployment: AWS EC2, RDS, S3",
                    "Capstone Project: Full Stack Enterprise Application",
                ],
            },
        ],
    },
    {
        "code": "WEBP",
        "name": "Web Dev with Python (Django)",
        "duration": 8,
        "fee": 45000,
        "description": "Learn Full Stack Web Development with Python's most popular web framework Django. This course covers everything from HTML/CSS front-end to Django back-end, REST APIs with Django REST Framework, and deploying to the cloud. Build real-world projects including social media platforms, e-commerce sites, and content management systems.",
        "prerequisites": [
            "Basic computer skills",
            "Familiarity with programming concepts",
        ],
        "learning_outcomes": [
            "Build dynamic websites with Django's MTV architecture",
            "Create RESTful APIs using Django REST Framework",
            "Implement authentication, authorization, and security",
            "Work with PostgreSQL, Redis, and caching systems",
            "Deploy Python web applications to production",
        ],
        "career_opportunities": [
            "Python Full Stack Developer",
            "Django Developer",
            "Backend Engineer",
            "DevOps Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Web Fundamentals & Python",
                "duration_weeks": 4,
                "topics": [
                    "Internet Fundamentals: HTTP/HTTPS, DNS, Client-Server Architecture",
                    "HTML5: Semantic Markup, Forms, APIs",
                    "CSS3: Styling, Flexbox, Grid, Responsive Design",
                    "JavaScript Basics: DOM, Events, Fetch API",
                    "Python Refresher: Data Types, Functions, OOP, Modules",
                    "Python Advanced: Decorators, Generators, Context Managers",
                    "Virtual Environments & Package Management with pip",
                ],
            },
            {
                "title": "Module 2: Django Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "Django Architecture: MVT Pattern, Project vs App",
                    "URL Routing: URLconfs, Named URLs, Namespaces",
                    "Views: Function-Based Views, Class-Based Views, Generic Views",
                    "Templates: Django Template Language, Template Inheritance, Filters",
                    "Models: ORM, Migrations, Relationships (ForeignKey, ManyToMany, OneToOne)",
                    "Forms: ModelForms, Form Validation, Widgets",
                    "Admin Interface: Customization, Inlines, Actions",
                    "Project: Blog Application with Full CRUD",
                ],
            },
            {
                "title": "Module 3: Advanced Django & Security",
                "duration_weeks": 5,
                "topics": [
                    "Authentication: User Model, Login/Logout, Password Management",
                    "Authorization: Permissions, Groups, Custom User Model",
                    "Sessions & Messages Framework",
                    "File Uploads: ImageField, FileField, Media Files",
                    "Signals: Built-in & Custom Signals",
                    "Middleware: Custom Middleware Development",
                    "Security: CSRF, XSS, SQL Injection Prevention, HTTPS",
                    "Caching: Memcached, Redis, Cache Framework",
                    "Project: E-Commerce Platform",
                ],
            },
            {
                "title": "Module 4: Django REST Framework & APIs",
                "duration_weeks": 4,
                "topics": [
                    "RESTful API Design Principles",
                    "Django REST Framework: Serializers, Viewsets, Routers",
                    "Authentication in APIs: Token, JWT, Session",
                    "Permissions & Throttling",
                    "Filtering, Searching, Ordering",
                    "API Documentation with drf-spectacular",
                    "Testing APIs with Postman & pytest",
                    "Project: Social Media API",
                ],
            },
            {
                "title": "Module 5: Deployment & DevOps",
                "duration_weeks": 4,
                "topics": [
                    "PostgreSQL: Setup, Configuration, Advanced Queries",
                    "Environment Variables & Settings Management",
                    "Docker: Containerization of Django Apps",
                    "Nginx & Gunicorn: Production Server Setup",
                    "AWS: EC2, RDS, S3 Static Files, Elastic Beanstalk",
                    "CI/CD: GitHub Actions, Automated Testing",
                    "Monitoring: Sentry, Logging, Performance Optimization",
                    "Capstone Project: Production-Ready Web Application",
                ],
            },
        ],
    },
    {
        "code": "MERN",
        "name": "MERN Stack Development",
        "duration": 10,
        "fee": 55000,
        "description": "Master the most popular JavaScript stack — MongoDB, Express.js, React, and Node.js. This comprehensive 10-month program takes you from JavaScript fundamentals to building full-stack single-page applications. Learn modern front-end development with React Hooks, state management with Redux, and scalable back-end APIs with Node.js and Express.",
        "prerequisites": [
            "Basic programming knowledge",
            "Familiarity with web concepts",
        ],
        "learning_outcomes": [
            "Build modern single-page applications with React 18",
            "Create scalable REST APIs with Node.js and Express",
            "Design schemas and work with MongoDB (NoSQL)",
            "Implement full authentication and authorization systems",
            "Deploy MERN applications to cloud platforms",
        ],
        "career_opportunities": [
            "MERN Stack Developer",
            "React Developer",
            "Node.js Backend Developer",
            "Full Stack JavaScript Developer",
        ],
        "modules": [
            {
                "title": "Module 1: JavaScript Deep Dive",
                "duration_weeks": 5,
                "topics": [
                    "ES6+ Syntax: Arrow Functions, Destructuring, Spread/Rest",
                    "Asynchronous JavaScript: Callbacks, Promises, Async/Await",
                    "Closures, Scope, Hoisting, Event Loop",
                    "Prototypal Inheritance & Classes",
                    "Modules: ES Modules, CommonJS",
                    "Error Handling & Debugging",
                    "Package Managers: npm & yarn",
                    "Project: JavaScript Utility Library",
                ],
            },
            {
                "title": "Module 2: React Front-End Development",
                "duration_weeks": 6,
                "topics": [
                    "React Fundamentals: JSX, Components, Props, State",
                    "React Hooks: useState, useEffect, useContext, useReducer",
                    "Custom Hooks Development",
                    "Conditional Rendering & Lists",
                    "Forms: Controlled Components, Form Libraries (Formik, React Hook Form)",
                    "React Router v6: Routing, Navigation, Guards",
                    "State Management: Context API vs Redux Toolkit",
                    "Styling: CSS Modules, Styled Components, Tailwind CSS",
                    "Project: Task Management Dashboard",
                ],
            },
            {
                "title": "Module 3: Node.js & Express Backend",
                "duration_weeks": 5,
                "topics": [
                    "Node.js: Event Loop, Streams, File System, Buffers",
                    "Express.js: Routing, Middleware, Error Handling",
                    "REST API Design & Best Practices",
                    "Authentication: JWT, OAuth 2.0, Sessions",
                    "File Uploads: Multer, Cloud Storage Integration",
                    "WebSockets with Socket.io",
                    "Testing: Jest, Supertest, Integration Tests",
                    "Project: Blog Platform API",
                ],
            },
            {
                "title": "Module 4: MongoDB & Database Design",
                "duration_weeks": 4,
                "topics": [
                    "NoSQL Concepts: Document Store, Collections, Documents",
                    "MongoDB: CRUD Operations, Aggregation Pipeline",
                    "Mongoose ODM: Schemas, Models, Validation",
                    "Relationships: Embedding vs Referencing",
                    "Indexing & Performance Optimization",
                    "MongoDB Atlas: Cloud Database Setup",
                    "Redis: Caching, Session Store",
                ],
            },
            {
                "title": "Module 5: Advanced Topics & Deployment",
                "duration_weeks": 5,
                "topics": [
                    "GraphQL: Schemas, Resolvers, Apollo Server & Client",
                    "TypeScript with React & Node.js",
                    "Next.js: SSR, SSG, API Routes",
                    "Docker: Multi-Container MERN Setup",
                    "AWS: EC2, S3, CloudFront, Route 53",
                    "CI/CD: GitHub Actions, Automated Deployment",
                    "Performance Optimization: Lazy Loading, Code Splitting",
                    "Capstone Project: Full Stack E-Commerce Platform",
                ],
            },
        ],
    },
    {
        "code": "DS",
        "name": "Data Science with Python",
        "duration": 12,
        "fee": 65000,
        "description": "Transform raw data into actionable insights with our comprehensive Data Science program. Learn Python programming, statistical analysis, machine learning, and deep learning. Work with real-world datasets, build predictive models, and create stunning data visualizations. This program is designed to create industry-ready data scientists.",
        "prerequisites": [
            "Basic mathematics (algebra, statistics)",
            "Logical thinking skills",
        ],
        "learning_outcomes": [
            "Manipulate and analyze data using Pandas and NumPy",
            "Build interactive visualizations with Matplotlib, Seaborn, and Plotly",
            "Apply machine learning algorithms to solve real-world problems",
            "Develop deep learning models with TensorFlow and PyTorch",
            "Deploy data science models to production",
        ],
        "career_opportunities": [
            "Data Scientist",
            "Machine Learning Engineer",
            "Data Analyst",
            "AI Research Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Python for Data Science",
                "duration_weeks": 5,
                "topics": [
                    "Python Refresher: Data Types, Functions, OOP",
                    "NumPy: Arrays, Vectorization, Broadcasting, Linear Algebra",
                    "Pandas: Series, DataFrames, GroupBy, Merge, Reshape",
                    "Data Cleaning: Handling Missing Values, Outliers, Duplicates",
                    "Data Wrangling: Pivot Tables, MultiIndex, String Operations",
                    "Exploratory Data Analysis (EDA) Techniques",
                    "Project: Exploratory Analysis of Real-World Dataset",
                ],
            },
            {
                "title": "Module 2: Statistics & Probability",
                "duration_weeks": 5,
                "topics": [
                    "Descriptive Statistics: Mean, Median, Mode, Variance, Standard Deviation",
                    "Probability Theory: Distributions (Normal, Binomial, Poisson)",
                    "Inferential Statistics: Confidence Intervals, Hypothesis Testing",
                    "Correlation & Covariance Analysis",
                    "Bayesian Statistics: Bayes Theorem, Naive Bayes",
                    "Statistical Tests: T-Test, Chi-Square, ANOVA",
                    "Feature Engineering: Scaling, Transformation, Encoding",
                ],
            },
            {
                "title": "Module 3: Data Visualization",
                "duration_weeks": 4,
                "topics": [
                    "Matplotlib: Figure, Axes, Subplots, Customization",
                    "Seaborn: Statistical Plots, Heatmaps, Pair Plots, FacetGrid",
                    "Plotly: Interactive Charts, Dashboards, Animations",
                    "Geographic Visualizations with Folium & Geopandas",
                    "Dashboard Creation with Dash/Streamlit",
                    "Storytelling with Data: Best Practices",
                    "Project: Interactive Data Dashboard",
                ],
            },
            {
                "title": "Module 4: Machine Learning Fundamentals",
                "duration_weeks": 6,
                "topics": [
                    "Supervised Learning: Linear Regression, Logistic Regression",
                    "Tree-Based Models: Decision Trees, Random Forest, XGBoost",
                    "Support Vector Machines (SVM): Kernels, Soft Margin",
                    "Unsupervised Learning: K-Means, Hierarchical Clustering, DBSCAN",
                    "Dimensionality Reduction: PCA, t-SNE, LDA",
                    "Model Evaluation: Cross-Validation, ROC Curves, Confusion Matrix",
                    "Hyperparameter Tuning: Grid Search, Random Search, Bayesian Optimization",
                    "Project: Predictive Modeling Challenge",
                ],
            },
            {
                "title": "Module 5: Deep Learning & Neural Networks",
                "duration_weeks": 6,
                "topics": [
                    "Neural Network Fundamentals: Perceptron, Activation Functions, Backpropagation",
                    "TensorFlow & Keras: Sequential API, Functional API",
                    "Convolutional Neural Networks (CNNs): Image Classification, Object Detection",
                    "Recurrent Neural Networks (RNNs): LSTM, GRU, Time Series",
                    "Natural Language Processing: Tokenization, Word Embeddings, Transformers",
                    "Transfer Learning & Fine-Tuning",
                    "Generative AI: GANs, Autoencoders",
                    "Project: Image Classification or NLP Application",
                ],
            },
            {
                "title": "Module 6: MLOps & Capstone Project",
                "duration_weeks": 4,
                "topics": [
                    "Model Deployment: Flask/FastAPI, Docker, AWS SageMaker",
                    "ML Pipelines: Feature Stores, Model Registry",
                    "Experiment Tracking with MLflow",
                    "Model Monitoring & Drift Detection",
                    "Big Data Tools: Spark, Dask",
                    "SQL for Data Scientists",
                    "Capstone Project: End-to-End Data Science Solution",
                ],
            },
        ],
    },
]
