# Courses 5-8

_courses_2 = [
    {
        "code": "DA",
        "name": "Data Analytics (Excel+SQL+BI)",
        "duration": 6,
        "fee": 35000,
        "description": "Kickstart your career in data analytics with this practical, hands-on program. Master Microsoft Excel (advanced formulas, pivot tables, macros), SQL (queries, database design), and Business Intelligence tools (Power BI, Tableau). Learn to transform raw data into actionable business insights and create professional dashboards.",
        "prerequisites": ["Basic computer literacy", "High school mathematics"],
        "learning_outcomes": [
            "Perform advanced data analysis using Excel functions and tools",
            "Write complex SQL queries to extract and manipulate data",
            "Create interactive dashboards with Power BI and Tableau",
            "Apply statistical analysis to business problems",
            "Present data-driven recommendations to stakeholders",
        ],
        "career_opportunities": [
            "Data Analyst",
            "Business Analyst",
            "BI Developer",
            "Reporting Analyst",
        ],
        "modules": [
            {
                "title": "Module 1: Advanced Excel Mastery",
                "duration_weeks": 5,
                "topics": [
                    "Excel Fundamentals: Formatting, Conditional Formatting, Data Validation",
                    "Advanced Formulas: VLOOKUP, INDEX-MATCH, XLOOKUP, INDIRECT",
                    "Logical Functions: IF, IFS, SWITCH, AND, OR, NOT",
                    "Text Functions: LEFT, RIGHT, MID, CONCATENATE, TEXTJOIN",
                    "Date & Time Functions: DATEDIF, WORKDAY, NETWORKDAYS",
                    "Statistical Functions: AVERAGEIF, COUNTIF, SUMIFS",
                    "Pivot Tables & Pivot Charts: Grouping, Slicers, Calculated Fields",
                    "Power Query: Data Transformation, Merging Queries",
                    "Macros & VBA: Recording, Editing, Automation",
                    "Project: Sales Dashboard in Excel",
                ],
            },
            {
                "title": "Module 2: SQL & Database Management",
                "duration_weeks": 5,
                "topics": [
                    "Database Fundamentals: Tables, Relationships, Normalization",
                    "SQL Basics: SELECT, WHERE, ORDER BY, LIMIT",
                    "Joins: INNER, LEFT, RIGHT, FULL OUTER, CROSS JOIN",
                    "Subqueries: Correlated vs Non-Correlated",
                    "Aggregation: GROUP BY, HAVING, Window Functions",
                    "CTEs (Common Table Expressions) & Recursive Queries",
                    "Views, Indexes, and Stored Procedures",
                    "Data Cleaning with SQL",
                    "Project: Business Database & Analytical Queries",
                ],
            },
            {
                "title": "Module 3: Power BI & Data Visualization",
                "duration_weeks": 4,
                "topics": [
                    "Power BI Desktop: Interface, Data Sources, Query Editor",
                    "Data Modeling: Relationships, Calculated Columns, Measures (DAX)",
                    "DAX Functions: CALCULATE, FILTER, ALL, RELATED, SUMX",
                    "Visualizations: Charts, Maps, Tables, Matrices, KPIs",
                    "Interactive Reports: Slicers, Drill-through, Bookmarks",
                    "Power BI Service: Publishing, Sharing, Workspaces",
                    "Project: Executive Sales Dashboard",
                ],
            },
            {
                "title": "Module 4: Business Analytics & Capstone",
                "duration_weeks": 4,
                "topics": [
                    "Introduction to Tableau: Worksheets, Dashboards, Stories",
                    "Statistical Analysis for Business: Regression, Forecasting",
                    "A/B Testing & Experimentation Design",
                    "Data Storytelling: Presentations & Communication",
                    "Case Studies: Real Business Problems",
                    "Capstone Project: End-to-End Analytics Solution",
                ],
            },
        ],
    },
    {
        "code": "CYBER",
        "name": "Cyber Security & Ethical Hack",
        "duration": 10,
        "fee": 60000,
        "description": "Protect the digital world with our comprehensive Cyber Security & Ethical Hacking program. Learn network security, penetration testing, vulnerability assessment, cryptography, and incident response. Gain hands-on experience with industry-standard tools like Kali Linux, Metasploit, and Wireshark in our dedicated lab environment.",
        "prerequisites": [
            "Basic networking knowledge",
            "Familiarity with Linux command line",
        ],
        "learning_outcomes": [
            "Conduct penetration tests on networks and web applications",
            "Identify and exploit vulnerabilities ethically",
            "Implement security measures to protect infrastructure",
            "Perform digital forensics and incident response",
            "Prepare for industry certifications (CEH, CompTIA Security+)",
        ],
        "career_opportunities": [
            "Ethical Hacker",
            "Security Analyst",
            "Penetration Tester",
            "Security Consultant",
            "CISO",
        ],
        "modules": [
            {
                "title": "Module 1: Networking & Security Fundamentals",
                "duration_weeks": 5,
                "topics": [
                    "Network Fundamentals: OSI Model, TCP/IP, Subnetting, VLANs",
                    "Network Protocols: HTTP, HTTPS, DNS, DHCP, ARP, ICMP",
                    "Firewalls: Types, Rules, Configuration (iptables, pfSense)",
                    "VPNs: Site-to-Site, Remote Access, WireGuard, OpenVPN",
                    "Linux Essentials: Command Line, File System, Permissions",
                    "Kali Linux: Installation, Tools Overview, Environment Setup",
                    "Virtualization: VMware, VirtualBox, Lab Network Setup",
                ],
            },
            {
                "title": "Module 2: Ethical Hacking & Reconnaissance",
                "duration_weeks": 5,
                "topics": [
                    "Footprinting & Reconnaissance: Passive Information Gathering",
                    "OSINT: Google Dorking, Shodan, Maltego, theHarvester",
                    "Network Scanning: Nmap, Masscan, Zenmap",
                    "Enumeration: NetBIOS, SNMP, LDAP, SMTP, DNS Enumeration",
                    "Vulnerability Scanning: Nessus, OpenVAS, Nikto",
                    "Social Engineering: Phishing, Pretexting, Physical Security",
                    "Practice: Complete Reconnaissance on a Target Network",
                ],
            },
            {
                "title": "Module 3: System Hacking & Exploitation",
                "duration_weeks": 5,
                "topics": [
                    "Password Cracking: John the Ripper, Hashcat, Hydra",
                    "Metasploit Framework: Modules, Payloads, Exploit Development",
                    "Buffer Overflow: Stack Overflow, SEH, ASLR Bypass",
                    "Windows Exploitation: Privilege Escalation, Persistence",
                    "Linux Exploitation: Kernel Exploits, SUID, Cron Jobs",
                    "Web Application Hacking: SQL Injection, XSS, CSRF, SSRF",
                    "Wireless Attacks: WPA2 Cracking, Evil Twin, Deauth Attack",
                    "Practice: Capture The Flag (CTF) Challenges",
                ],
            },
            {
                "title": "Module 4: Digital Forensics & Incident Response",
                "duration_weeks": 5,
                "topics": [
                    "Digital Forensics Methodology: Identification, Preservation, Analysis",
                    "Disk Forensics: EnCase, FTK Imager, Autopsy, Sleuth Kit",
                    "Memory Forensics: Volatility, Dump Analysis",
                    "Network Forensics: Wireshark, tcpdump, Network Miner",
                    "Incident Response Lifecycle: Preparation, Detection, Containment, Eradication",
                    "Malware Analysis: Static, Dynamic, Reverse Engineering Basics",
                    "Cyber Law & Compliance: GDPR, IT Act, ISO 27001",
                ],
            },
            {
                "title": "Module 5: Advanced Security & Capstone",
                "duration_weeks": 4,
                "topics": [
                    "Cryptography: Symmetric, Asymmetric, Hashing, PKI",
                    "Cloud Security: AWS, Azure Security Best Practices",
                    "DevSecOps: Integrating Security in CI/CD Pipeline",
                    "SIEM: Splunk, ELK Stack, Security Monitoring",
                    "Bug Bounty: Methodology, Platforms (HackerOne, Bugcrowd)",
                    "Certification Preparation: CEH, CompTIA Security+, OSCP",
                    "Capstone Project: Full Penetration Test Report",
                ],
            },
        ],
    },
    {
        "code": "AIML",
        "name": "AI & Machine Learning",
        "duration": 12,
        "fee": 75000,
        "description": "Dive deep into the world of Artificial Intelligence and Machine Learning. This comprehensive program covers everything from classical ML algorithms to cutting-edge deep learning, natural language processing, computer vision, and generative AI. Work with TensorFlow, PyTorch, and Hugging Face to build intelligent systems that solve real-world problems.",
        "prerequisites": [
            "Python programming experience",
            "Linear algebra & calculus basics",
            "Statistics fundamentals",
        ],
        "learning_outcomes": [
            "Build and deploy machine learning models end-to-end",
            "Develop deep neural networks for complex tasks",
            "Implement NLP pipelines for text processing and generation",
            "Create computer vision applications for image and video analysis",
            "Work with transformer models and large language models",
        ],
        "career_opportunities": [
            "Machine Learning Engineer",
            "AI Research Scientist",
            "Deep Learning Engineer",
            "Computer Vision Engineer",
            "NLP Engineer",
        ],
        "modules": [
            {
                "title": "Module 1: Mathematics for Machine Learning",
                "duration_weeks": 5,
                "topics": [
                    "Linear Algebra: Vectors, Matrices, Eigenvalues, SVD",
                    "Calculus: Derivatives, Gradients, Chain Rule, Partial Derivatives",
                    "Probability & Statistics: Distributions, Bayes Theorem, MLE",
                    "Optimization: Gradient Descent, SGD, Adam, RMSprop",
                    "Information Theory: Entropy, KL Divergence, Cross-Entropy",
                    "Python Review: NumPy, SciPy, Matplotlib for ML",
                ],
            },
            {
                "title": "Module 2: Classical Machine Learning",
                "duration_weeks": 6,
                "topics": [
                    "Supervised Learning: Linear Regression, Ridge, Lasso",
                    "Classification: Logistic Regression, Decision Trees, Random Forest",
                    "Support Vector Machines: Kernels, Soft Margin, SVR",
                    "Ensemble Methods: Bagging, Boosting, AdaBoost, XGBoost, LightGBM",
                    "Unsupervised Learning: K-Means, DBSCAN, Hierarchical Clustering",
                    "Dimensionality Reduction: PCA, t-SNE, UMAP",
                    "Model Evaluation: Cross-Validation, Grid Search, Metrics",
                    "Feature Engineering & Selection Techniques",
                    "Project: ML Model for Tabular Data",
                ],
            },
            {
                "title": "Module 3: Neural Networks & Deep Learning",
                "duration_weeks": 6,
                "topics": [
                    "Neural Network Architecture: Layers, Activation Functions, Loss Functions",
                    "Backpropagation: Chain Rule, Gradient Computation, Automatic Differentiation",
                    "TensorFlow 2.x: Keras API, Custom Training Loops, tf.data",
                    "PyTorch: Tensors, Autograd, nn.Module, DataLoader",
                    "Regularization: Dropout, Batch Normalization, L1/L2",
                    "Advanced Architectures: ResNet, Inception, EfficientNet",
                    "Transfer Learning & Fine-Tuning Pre-trained Models",
                    "Hyperparameter Optimization: Optuna, Keras Tuner",
                    "Project: Image Classification with CNN",
                ],
            },
            {
                "title": "Module 4: Natural Language Processing",
                "duration_weeks": 5,
                "topics": [
                    "Text Processing: Tokenization, Stemming, Lemmatization, Stop Words",
                    "Word Embeddings: Word2Vec, GloVe, FastText",
                    "RNNs, LSTMs, GRUs for Sequence Modeling",
                    "Attention Mechanism & Transformer Architecture",
                    "BERT, GPT, T5: Pre-trained Language Models",
                    "Hugging Face: Transformers Library, Pipeline, Fine-tuning",
                    "NLP Tasks: Text Classification, NER, Question Answering, Summarization",
                    "Project: Sentiment Analysis & Text Generation System",
                ],
            },
            {
                "title": "Module 5: Computer Vision",
                "duration_weeks": 5,
                "topics": [
                    "Image Processing: OpenCV, Filtering, Edge Detection",
                    "CNN Architectures: AlexNet, VGG, ResNet, Inception",
                    "Object Detection: YOLO, SSD, Faster R-CNN",
                    "Image Segmentation: U-Net, Mask R-CNN",
                    "Generative Models: GANs, VAEs, Diffusion Models",
                    "Vision Transformers (ViT)",
                    "Video Analysis: Action Recognition, Object Tracking",
                    "Project: Real-Time Object Detection System",
                ],
            },
            {
                "title": "Module 6: MLOps & Capstone Project",
                "duration_weeks": 5,
                "topics": [
                    "ML Pipeline: Data Versioning (DVC), Feature Store",
                    "Experiment Tracking: MLflow, Weights & Biases",
                    "Model Deployment: FastAPI, Docker, Kubernetes",
                    "Cloud AI Services: AWS SageMaker, GCP AI Platform",
                    "Model Monitoring: Drift Detection, Performance Metrics",
                    "Responsible AI: Fairness, Bias, Explainability (SHAP, LIME)",
                    "Generative AI: Prompt Engineering, LangChain, RAG",
                    "Capstone Project: End-to-End AI Solution",
                ],
            },
        ],
    },
    {
        "code": "CLOUD",
        "name": "Cloud Computing (AWS+Azure)",
        "duration": 8,
        "fee": 50000,
        "description": "Master cloud computing with hands-on training on AWS and Microsoft Azure. Learn to design, deploy, and manage scalable cloud infrastructure. Cover core services, networking, security, storage, compute, serverless computing, containers, and DevOps practices. Prepare for industry certifications like AWS Solutions Architect and Azure Administrator.",
        "prerequisites": [
            "Basic IT infrastructure knowledge",
            "Networking fundamentals",
        ],
        "learning_outcomes": [
            "Design and implement cloud architectures on AWS and Azure",
            "Configure virtual networks, security groups, and IAM policies",
            "Deploy and manage containers with Docker and Kubernetes",
            "Implement CI/CD pipelines for cloud applications",
            "Optimize cloud costs and implement best practices",
        ],
        "career_opportunities": [
            "Cloud Architect",
            "DevOps Engineer",
            "Cloud Engineer",
            "Site Reliability Engineer (SRE)",
        ],
        "modules": [
            {
                "title": "Module 1: Cloud Computing Fundamentals",
                "duration_weeks": 4,
                "topics": [
                    "Cloud Computing Models: IaaS, PaaS, SaaS, FaaS",
                    "Deployment Models: Public, Private, Hybrid, Multi-Cloud",
                    "AWS Global Infrastructure: Regions, AZs, Edge Locations",
                    "Azure Global Infrastructure: Regions, Availability Zones",
                    "AWS Free Tier & Account Setup",
                    "Azure Free Account & Portal Overview",
                    "Billing & Cost Management: AWS Cost Explorer, Azure Cost Management",
                    "Cloud Security Shared Responsibility Model",
                ],
            },
            {
                "title": "Module 2: Compute & Storage Services",
                "duration_weeks": 5,
                "topics": [
                    "AWS EC2: Instance Types, AMIs, Security Groups, EBS",
                    "Azure VMs: Sizes, Disks, Availability Sets",
                    "AWS S3: Buckets, Objects, Versioning, Lifecycle Policies",
                    "Azure Blob Storage: Containers, Access Tiers, Replication",
                    "AWS EBS & EFS: Block vs File Storage",
                    "Azure Files & Azure Disk Storage",
                    "AWS RDS: Databases, Multi-AZ, Read Replicas",
                    "Azure SQL Database: Elastic Pools, Managed Instance",
                    "AWS Lambda: Serverless Functions, Triggers",
                    "Azure Functions: Triggers, Bindings, Durable Functions",
                ],
            },
            {
                "title": "Module 3: Networking & Security",
                "duration_weeks": 5,
                "topics": [
                    "AWS VPC: Subnets, Route Tables, NAT Gateways, Internet Gateways",
                    "Azure VNet: Subnets, Peering, VPN Gateway",
                    "AWS IAM: Users, Groups, Roles, Policies, MFA",
                    "Azure AD: Identity, RBAC, Managed Identities",
                    "AWS ELB & ALB: Load Balancers, Target Groups, Health Checks",
                    "Azure Load Balancer: Public, Internal, Application Gateway",
                    "AWS CloudFront: CDN, Behaviors, Origin Access",
                    "Azure CDN: Profiles, Endpoints, Rules Engine",
                    "AWS WAF & Shield: Web ACLs, DDoS Protection",
                    "Azure Firewall & DDoS Protection",
                ],
            },
            {
                "title": "Module 4: Containers & DevOps",
                "duration_weeks": 5,
                "topics": [
                    "Docker: Images, Containers, Dockerfile, Docker Compose",
                    "Amazon ECR: Container Registry, Image Scanning",
                    "Azure Container Registry: Repositories, Tasks",
                    "Amazon ECS: Task Definitions, Services, Fargate",
                    "Azure Container Instances & AKS",
                    "Kubernetes: Pods, Deployments, Services, ConfigMaps",
                    "Infrastructure as Code: AWS CloudFormation, Terraform",
                    "CI/CD: AWS CodePipeline, Azure DevOps Pipelines",
                    "Configuration Management: Ansible, AWS Systems Manager",
                    "Monitoring: CloudWatch, Azure Monitor, Prometheus, Grafana",
                ],
            },
            {
                "title": "Module 5: Advanced Topics & Certification",
                "duration_weeks": 3,
                "topics": [
                    "AWS Lambda Advanced: Layers, VPC Integration, Step Functions",
                    "Azure Logic Apps & Power Automate",
                    "API Gateway: AWS API Gateway, Azure API Management",
                    "Disaster Recovery: Backup, Multi-Region, RTO/RPO",
                    "Cost Optimization: Reserved Instances, Spot Instances, Savings Plans",
                    "AWS Well-Architected Framework",
                    "Azure Well-Architected Framework",
                    "Certification Preparation: AWS SAA, Azure AZ-104",
                    "Capstone Project: Multi-Tier Cloud Architecture Implementation",
                ],
            },
        ],
    },
]
